# I include this file for the test task to work out of the box
# I promice I will not do this in production

apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
data:
  APP_SECRET_KEY: VVNFX1lPVVJfU0VDUkVUX0tFWQ==